### ISSUE TITLE
使用最新版node.dll报错

### ISSUE THREAD

**Issue by Leezj9671** [ynyyn/Miniblink-Python-SimpleDemo#2]
使用的miniblink版本为 2019.11.22版
1. 使用 `node.dll `时报错如下：
```                                       
λ python miniblink.py                                                              
Exception in thread Thread-1:                                                      
Traceback (most recent call last):                                                 
  File "D:\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner              
    self.run()                                                                     
  File "miniblink.py", line 16, in run                                             
    mb = ctypes.cdll.LoadLibrary("node.dll")                                       
  File "D:\Anaconda3\lib\ctypes\__init__.py", line 442, in LoadLibrary             
    return self._dlltype(name)                                                     
  File "D:\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__                
    self._handle = _dlopen(self._name, mode)                                       
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。                                       
``` 
2. 使用 `miniblink_x64.dll` 报错如下                                         
```
λ python miniblink.py                                                              
Exception in thread Thread-1:                                                      
Traceback (most recent call last):                                                 
  File "D:\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner              
    self.run()                                                                     
  File "miniblink.py", line 24, in run                                             
    mb.wkeMoveToCenter(webview)                                                    
OSError: exception: access violation reading 0x000000007A54EE08                    
```                                                                                   
请问该如何解决？

**Comment by ynyyn** [comment]
### 关于  1. 中所出现的错误

经测试，2019.11.22 版本的 node.dll 可以在 Python 3.7 (32 bit) 上运行。

根据您提供的错误信息，导致 1. 错误的原因很可能是您使用了 64 位的 Python 运行该脚本。32 位的动态链接库（node.dll）需要配套使用 32 位的 Python 才能加载。 

### 关于 2. 中所出现的错误

受制于 ctypes 库的一些固有特性，目前本 Demo 需要略作修改才能切换到 64 位使用，无法直接迁移运行，即便您使用 64 位的 Python 和配套的 64 位的动态链接库（miniblink_x64.dll）。

更多技术细节，可参阅 issue #3

**Comment by Leezj9671** [comment]
那么，除了更换 python 版本为32位，在 demo 中应该怎么修改呢

**Comment by ynyyn** [comment]
> 
> 
> 那么，除了更换 python 版本为32位，在 demo 中应该怎么修改呢

参阅上文提到的 issue，文末有给出修改方向，不是很复杂的。

**Comment by Leezj9671** [comment]
感谢！已解决！
